### PR TITLE
[CI] Use sudo

### PR DESCRIPTION
**Pull request by azime**

### CODE REVIEW

**Review by benoit-bst — COMMENTED** [review]
It is mandatory ? Why a sudo is necessary ?

**Comment by azime** [comment]
See: [CI](https://github.com/CanalTP/mimirsbrunn/runs/2200119320?check_suite_focus=true)

**Comment by benoit-bst** [comment]
Okay, but I don't understand why. 
We code GA flow, from the beginning, without sudo. We can see examples inside Navitia project.
I don't see the difference between this 2 projects and why Sudo is necessary for imirsbrunn

**Comment by azime** [comment]
In Navitia, we use containers

**Review by benoit-bst — APPROVED** [review]

**Review by pbench — APPROVED** [review]

**Pull request merged**
