### PR TITLE
Remove a verbose useless log

### PR DESCRIPTION
**Pull request by jbgriesner**
A recent PR https://github.com/CanalTP/mimirsbrunn/pull/226 added a too verbose log in case of an ignored address.

This PR just remove the useless part of this log.
The change in the log has no impact on the existing tests, so no test comes along this small fix.

### CODE REVIEW

**Comment by buildbotctp** [comment]
Can one of the admins verify this patch?

**Comment by TeXitoi** [comment]
fmt doesn't pass. Please change line 15 of .travis.yml to stable, for stable fmt, it will be more... stable ;-)

**Comment by antoine-de** [comment]
I'd have to reformat all my PRs again :sob:

**Comment by TeXitoi** [comment]
@antoine-de long term you'll have to reformat less

**Comment by jbgriesner** [comment]
fmt should be ok now.
Just to be clear, the "real" change of this PR is line 135 in  "src/bin/openaddresses2mimir.rs".

**Pull request merged**
