### PR TITLE
Merge physical_modes, commercial_modes, codes and properties for global_stop_index

### PR DESCRIPTION
**Pull request by xlqian**
https://jira.canaltp.fr/browse/NAVP-809

This PR will avoid to have duplicated info( physical_modes, commercial_modes, codes, properties) in `global_stop_index` when you import(`stop2mimir` or `ntfs2mimir`) stops from different sources and those stops' IDs are the same.

### CODE REVIEW

**Comment by antoine-de** [comment]
The JIRA link is a bit difficult to read for exterior contributors :stuck_out_tongue_winking_eye:

**Comment by TeXitoi** [comment]
There is nothing interesting in JIRA.

**Comment by xlqian** [comment]
@antoine-de Sorry for that, but you can read the code to understand! xD

**Comment by xlqian** [comment]
@antoine-de I'm adding some blabla...

**Comment by antoine-de** [comment]
great, I love blabla! :laughing:

**Pull request merged**
