### PR TITLE
Add nb to the id to prevent "disappearances" of elements at the same position

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by antoine-de** [comment]
I see the point of this change, but:
* Even with the retro-compatibility stuff, I'd like to check if kisio can use it, of if it will break stuff on their side.
* Is adding the house number sufficient here ? Won't we have other problems for different streets too ?

You changed it for bano, but it would be better to do it also for openaddresses too

**Comment by GuillaumeGomez** [comment]
With this, on bano we still have around 12K duplicates. This is not good enough. The only way to efficiently de-duplicate would certainly be to put the street's name inside the id...

**Comment by kinnou02** [comment]
> With this, on bano we still have around 12K duplicates. This is not good enough. The only way to efficiently de-duplicate would certainly be to put the street's name inside the id...

for bano we could use the fantoir, it will be less hideous...

**Comment by GuillaumeGomez** [comment]
What is the "fantoir"?

**Comment by kinnou02** [comment]
https://wiki.openstreetmap.org/wiki/FR:Key:ref:FR:FANTOIR
it's more or less an id of street in France

**Comment by GuillaumeGomez** [comment]
Oh I see! Wouldn't it be better to have something that would work for both openaddresses and bano?

**Comment by GuillaumeGomez** [comment]
So with the id, we have around 2K cases where the position and the number is the same, but not the street name. In those cases, a lot are coming from errors. With this information; is it worth it trying to make something more advanced? With this PR, we handle more than 99.9999% of the addresses.

**Comment by kinnou02** [comment]
I don't think it is worth it.

**Comment by antoine-de** [comment]
if we really don't want duplicates, why don't we use an `uuid` (or even better, let ES handle it by not supplying the id (the only argument for a manual id would be to keep `coord:<uuid>`)) ?

I don't really see where this could cause some problem.

any thoughts @kinnou02 @amatissart @GuillaumeGomez ?

**Comment by GuillaumeGomez** [comment]
Are we supposed to be able to easily find an object or not? Because currently it's possible, using a uuid would make it very complicated.

**Comment by amatissart** [comment]
On our side these ids will be used in URLs (https://www.qwant.com/maps/place/addr:2.307281;48.870237), stored in user favorites, etc.  

So we'd like to keep deterministic stable ids (as far as possible), and ideally not related to a particular data source, to be able to switch or merge other sources in the future.

**Comment by antoine-de** [comment]
I did some tests on navitia, the formatting of the id does not seems to be a problem, we'll be soon able to merge this PR, sorry for the delay!

**Pull request merged**
